trigger:
  - releases/*

jobs:
  # - job: macos_build
  #   displayName: "Build for macOS"
  #   pool:
  #     vmImage: "macOS-10.14"
  #   strategy:
  #     matrix:
  #       x64:
  #         TARGET_ARCH: x64
  #   variables:
  #     qt5_install_dir: /usr/local/Cellar/qt/5.12.3
  #     qt5_brew_formula: https://raw.githubusercontent.com/Homebrew/homebrew-core/65a45a9e61f15046a256cdba6a008f38f79570c9/Formula/qt.rb
  #   steps:
  #     - task: NodeTool@0
  #       inputs:
  #         versionSpec: 12.x
  #     - script: curl -O $(qt5_brew_formula) && brew install ./qt.rb
  #     - script: TARGET_ARCH=$(TARGET_ARCH) HOST_ARCH=$(TARGET_ARCH) QT_INSTALL_DIR=$(qt5_install_dir) node build.js

  - job: linux_build
    displayName: 'Build for Linux'
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        x64:
          TARGET_ARCH: x64
    steps:
    - script: |
        docker build -t qode-linux .
        docker run --rm qode-linux:latest tar -cC /usr/local/qt5/ . | tar -xC ~
        ls ~
    
# jobs:
# - job: windows_build
#   displayName: 'Build for Windows'
#   pool:
#     vmImage: 'VS2017-Win2016'
#   strategy:
#     matrix:
#       x64:
#         TARGET_ARCH: x64
#       ia32:
#         TARGET_ARCH: ia32
#   timeoutInMinutes: 120
#   cancelTimeoutInMinutes: 120
#   steps:
#   - template: azure-pipelines-template.yml
#   - script: out\Release\qode.exe test.js
#     displayName: Run tests

# - job: macos_build
#   displayName: 'Build for macOS'
#   pool:
#     vmImage: 'macOS-10.13'
#   strategy:
#     matrix:
#       x64:
#         TARGET_ARCH: x64
#   steps:
#   - template: azure-pipelines-template.yml
#   - script: out/Release/qode test.js
#     displayName: Run tests

# - job: linux_build
#   displayName: 'Build for Linux'
#   pool:
#     vmImage: 'ubuntu-16.04'
#   strategy:
#     matrix:
#       x64:
#         TARGET_ARCH: x64
#   steps:
#   - script: |
#       sudo apt-get update
#       sudo apt-get install -y libgtk-3-dev
#     displayName: Install dependencies
#   - template: azure-pipelines-template.yml
#   - script: xvfb-run out/Release/qode test.js
#     displayName: Run tests

